# Generated by Django 3.2.18 on 2023-03-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='name',
        ),
        migrations.AddField(
            model_name='wallets',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='currency',
            field=models.CharField(max_length=25),
        ),
    ]
