# Generated by Django 3.2.18 on 2023-03-24 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallets_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('wallet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.wallets')),
            ],
        ),
    ]
