# Generated by Django 3.2.18 on 2023-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_auto_20230329_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
